services:
  vulnogram-mongo:
    image: mongo:6
    command: mongod --port ${MONGO_PORT:-27017}
    restart: always
    env_file:
      - ${ENV_VAR_PATH:-example.env}
    volumes:
      - vulnogram-mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT:-27017}/vulnogram --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}

  vulnogram:
    image: ghcr.io/lancemccarthy/vulnogram:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: vulnogram
    env_file:
      - ${ENV_VAR_PATH:-example.env}
    ports:
      - ${VULNOGRAM_PORT:-3555}:${VULNOGRAM_PORT:-3555}
    depends_on:
      vulnogram-mongo:
        condition: service_healthy

volumes:
  vulnogram-mongo-data:
